describe('dns primitives', function()
	local dns = require('dns')

	it('library constants', function ()
		assert.same(1, dns.class.IN)
		assert.same(1, dns.class['IN'])
		assert.same('IN', dns.tostring.class[1])
		assert.falsy(dns.tostring.class[666666])
		assert.same(2, dns.type.NS)
		assert.same('NS', dns.tostring.type[2])
		assert.same(2, dns.rcode.SERVFAIL)
		assert.same('SERVFAIL', dns.tostring.rcode[2])
		assert.same(0, dns.opcode.QUERY)
		assert.same('QUERY', dns.tostring.opcode[0])
		-- Check metatypes
		assert.truthy(dns.type.ismeta(dns.type.AXFR))
		assert.truthy(dns.type.ismeta(dns.type.OPT))
		assert.falsy(dns.type.ismeta(dns.type.A))
		assert.falsy(dns.type.ismeta(40000))
	end)
end)
